
###
POST http://localhost:8000/api/user/registration
Content-Type: application/json

{   
    "username": "us2er0112",
    "password": "Abc12345",
    "firstname": "juan",
    "lastname": "Dela Cruz",
    "address": "juan@email.com",
    "contact": "099933201456"

}

###
POST http://localhost:8000/api/user/login
Content-Type: application/json

{
  "username": "us2er0112",
  "password": "Abc12345"
}

###
GET http://localhost:8000/coochie
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTEzNWZmNjEwYzdjMzI2ZGZiYzc3NWYiLCJkZXZpY2UiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTYzOTgyODExMX0.nEKcxb2DtH5iKWnN2r0nwmOxqpuJFrjcO2S2Af0XQ3w


###
PATCH http://localhost:8000/api/user/information 
Authorization: Bearerey eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJfaWQiOiI2MTEyMmYzMzg4ZTQ4ZDhkZjVlOWQ4OWEiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsInNob3AiOiI2MTEyMmYzMzg4ZTQ4ZDhkZjVlOWQ4OWIifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg2MDM4NDl9.Ydfk450GWI4U_2oJ8MFCe4CAWiTvWqgJQp6bXCyFwsE
Content-Type: application/json

{   
    "username": "us2er01s12",
    "password": "Abc12345",
    "firstname": "juan",
    "lastname": "Dela Cruz",
    "email": "gybeasdasd@gmail.com",
    "contact": "0999321456"
}
###
GET http://localhost:8000/api/user/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMWMxOTcwYjllZDUxNWYzMjM0N2IxIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRSNjI4TU9DTFlydURoVGlGV2kzQ3p1WU1YODBIeW5TOTZtNFpTZ3FuSjhHU2w4dlI5UEdBaSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMTQ1NiIsInNob3AiOiI2MTExYzE5NzBiOWVkNTE1ZjMyMzQ3YjIiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTEwVDAwOjAwOjIzLjY1OFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTEwVDAwOjAwOjIzLjY1OFoifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg1NjUyNTB9.WDHP5zO0dkTHEAt2AupK03Lx6dqD4jx25AofUi9AXJ8

###
GET http://localhost:8000/api/shop/info/611089aebf403a5ebd342915


###
PATCH http://localhost:8000/api/shop/info
Authorization: Bearerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMDg5YWViZjQwM2E1ZWJkMzQyOTE0IiwidXNlcm5hbWUiOiJ1c2VyMDEiLCJwYXNzd29yZCI6IiQyYSQxMCRDOVJpSEdVRnhSTm5vOWlpaDlRcWdlc2c2REg2UWFBT2hlS1NJaVNkTlgxb3BTUHdFNkpYVyIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMTQ1NiIsInNob3AiOiI2MTEwODlhZWJmNDAzYTVlYmQzNDI5MTUiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg0NzM3Nzh9.siuyW3xrNYCo8XACmRPRwOuyqR2xJ-Lz2vfHrj2_8Kg
Content-Type: application/json

{
  "location": ["taytay,rizal","pasig","quezon"],
  "name": "Sample 1" 
}

###
GET http://localhost:8000/api/shop/search/0
Content-Type: application/json

{
  "location": "taytay,rizal"
}
###
POST http://localhost:8000/api/shop/product
Authorization: Bearerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMDg5YWViZjQwM2E1ZWJkMzQyOTE0IiwidXNlcm5hbWUiOiJ1c2VyMDEiLCJwYXNzd29yZCI6IiQyYSQxMCRDOVJpSEdVRnhSTm5vOWlpaDlRcWdlc2c2REg2UWFBT2hlS1NJaVNkTlgxb3BTUHdFNkpYVyIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMTQ1NiIsInNob3AiOiI2MTEwODlhZWJmNDAzYTVlYmQzNDI5MTUiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg0NzM3Nzh9.siuyW3xrNYCo8XACmRPRwOuyqR2xJ-Lz2vfHrj2_8Kg
Content-Type: application/json

{   
   "name": "something",
   "descriptions": "something",
   "wallpaper": "something",
   "variants": [
     {"name": "1", "img": "2", "price": 0}
   ]
}


####
GET  http://localhost:8000/api/shop/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbIjYxMGY1YTJhNDQwYzJlMzRlNDdlOGY4NCIsIjYxMGY2NTQ2OWE4NWJhNDc1NTcyOTM5YyIsIjYxMGY2NTUzOWE4NWJhNDc1NTcyOTM5ZCJdLCJwcm9maWxlSU1HIjoiaHR0cDovL3NuYXAuc2hvL3Nhbi5qcGciLCJzYW1wbGUiOiJub3QgY2hhbmdlIiwiX2lkIjoiNjEwY2JhOTI4ZmI1Nzg2NTZjOGEyZmRiIiwidXNlcm5hbWUiOiJzYW1wbGUiLCJwYXNzd29yZCI6IiQyYSQxMCRPYVhMdnZLYUNXbm9aSjdxUUliZWQuT2c5ZkdYbWd0T2ZmN2NMd3FDcldZQ3NRL1ExSnd3RyIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJneWJlMTJAZ21hMGlsLmNvbSJ9LCJkZXZpY2UiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTYyODQxODY5MX0.QIyHjhnJ2mBJm1OOzVgnrRnOyzc9y1AfhLVMcxUgpyM

###
GET http://localhost:8000/api/msg/610f5a2a440c2e34e47e8f84/2



###
GET  http://localhost:8000/api/inbox/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{
  "shop": "6111c1970b9ed515f32347b2"
}

###
GET http://localhost:8000/api/inbox/userMsgs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc

###
GET  http://localhost:8000/api/inbox/msgs/61139cbac5817733e870ff5e/1/shop
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc

###
POST http://localhost:8000/api/inbox/61139cbac5817733e870ff5e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{
  "from": "customer",
  "body": "samp2le"
}


###
POST http://localhost:8000/api/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{
  "name": "product name",
  "mainImg": "link to main img",
  "descriptions": "product description",
  "variants": [
    {"name": "variant type 1", "price": 100, "img": "link to img"},
    {"name": "variant type 2", "price": 100, "img": "link 2 img"} 
  ]
}


###
GET http://localhost:8000/api/product/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc

###
GET http://localhost:8000/api/product/info/611779b7d4ab5f20caa24fea

###
PATCH  http://localhost:8000/api/product/info/611779b7d4ab5f20caa24fea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{"variants": []}

###
DELETE http://localhost:8000/api/product/611779b7d4ab5f20caa24fea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json



###
POST http://localhost:8000/api/order/new/61122f3388e48d8df5e9d89b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{
  "shop": "shopId",
  "items": [
    {
      "product": "[productId]", 
      "variant": "variant", 
      "price":100, 
      "quantity": 100, 
      "subTotal": 100}
  ],
  "total": 100000
}

###
GET http://localhost:8000/api/order/shop
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

###
GET http://localhost:8000/api/order/info/61175da2a4c81d1227d6c8f7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json


###
PATCH http://localhost:8000/api/order/status/61175da2a4c81d1227d6c8f7/-1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json


###
DELETE http://localhost:8080/api/order/[orderId]
Authorization: Bearer [token]
Content-Type: application/json


###
