
###
GET http://localhost:8000/api/msg/610f5a2a440c2e34e47e8f84/2



###
GET  http://localhost:8000/api/inbox/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{
  "shop": "6111c1970b9ed515f32347b2"
}

###
GET http://localhost:8000/api/inbox/userMsgs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc

###
GET  http://localhost:8000/api/inbox/msgs/61139cbac5817733e870ff5e/1/shop
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc

###
POST http://localhost:8000/api/inbox/61139cbac5817733e870ff5e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{
  "from": "customer",
  "body": "samp2le"
}

