
###
POST http://localhost:8000/api/order/new/61122f3388e48d8df5e9d89b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

{
  "shop": "shopId",
  "items": [
    {
      "product": "[productId]", 
      "variant": "variant", 
      "price":100, 
      "quantity": 100, 
      "subTotal": 100}
  ],
  "total": 100000
}

###
GET http://localhost:8000/api/order/shop
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json

###
GET http://localhost:8000/api/order/info/61175da2a4c81d1227d6c8f7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json


###
PATCH http://localhost:8000/api/order/status/61175da2a4c81d1227d6c8f7/-1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODlhIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMDE0NTYiLCJzaG9wIjoiNjExMjJmMzM4OGU0OGQ4ZGY1ZTlkODliIiwiY3JlYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOC0xMFQwNzo0ODowMy41MDBaIn0sImRldmljZSI6InZzY29kZS1yZXN0Y2xpZW50IiwiaWF0IjoxNjI4NTkxNDc4fQ.r2unpUwM_xh-ofyhWTKlgDiVq9Is3wjY1UykzmXYmbc
Content-Type: application/json


###
DELETE http://localhost:8080/api/order/[orderId]
Authorization: Bearer [token]
Content-Type: application/json

