
###
GET http://localhost:8000/api/shop/info/611089aebf403a5ebd342915


###
PATCH http://localhost:8000/api/shop/info
Authorization: Bearerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMDg5YWViZjQwM2E1ZWJkMzQyOTE0IiwidXNlcm5hbWUiOiJ1c2VyMDEiLCJwYXNzd29yZCI6IiQyYSQxMCRDOVJpSEdVRnhSTm5vOWlpaDlRcWdlc2c2REg2UWFBT2hlS1NJaVNkTlgxb3BTUHdFNkpYVyIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMTQ1NiIsInNob3AiOiI2MTEwODlhZWJmNDAzYTVlYmQzNDI5MTUiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg0NzM3Nzh9.siuyW3xrNYCo8XACmRPRwOuyqR2xJ-Lz2vfHrj2_8Kg
Content-Type: application/json

{
  "location": ["taytay,rizal","pasig","quezon"],
  "name": "Sample 1" 
}

###
GET http://localhost:8000/api/shop/search/0
Content-Type: application/json

{
  "location": "taytay,rizal"
}
###
POST http://localhost:8000/api/shop/product
Authorization: Bearerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMDg5YWViZjQwM2E1ZWJkMzQyOTE0IiwidXNlcm5hbWUiOiJ1c2VyMDEiLCJwYXNzd29yZCI6IiQyYSQxMCRDOVJpSEdVRnhSTm5vOWlpaDlRcWdlc2c2REg2UWFBT2hlS1NJaVNkTlgxb3BTUHdFNkpYVyIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMTQ1NiIsInNob3AiOiI2MTEwODlhZWJmNDAzYTVlYmQzNDI5MTUiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTA5VDAxOjQ5OjM0Ljc1MloifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg0NzM3Nzh9.siuyW3xrNYCo8XACmRPRwOuyqR2xJ-Lz2vfHrj2_8Kg
Content-Type: application/json

{   
   "name": "something",
   "descriptions": "something",
   "wallpaper": "something",
   "variants": [
     {"name": "1", "img": "2", "price": 0}
   ]
}


####
GET  http://localhost:8000/api/shop/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbIjYxMGY1YTJhNDQwYzJlMzRlNDdlOGY4NCIsIjYxMGY2NTQ2OWE4NWJhNDc1NTcyOTM5YyIsIjYxMGY2NTUzOWE4NWJhNDc1NTcyOTM5ZCJdLCJwcm9maWxlSU1HIjoiaHR0cDovL3NuYXAuc2hvL3Nhbi5qcGciLCJzYW1wbGUiOiJub3QgY2hhbmdlIiwiX2lkIjoiNjEwY2JhOTI4ZmI1Nzg2NTZjOGEyZmRiIiwidXNlcm5hbWUiOiJzYW1wbGUiLCJwYXNzd29yZCI6IiQyYSQxMCRPYVhMdnZLYUNXbm9aSjdxUUliZWQuT2c5ZkdYbWd0T2ZmN2NMd3FDcldZQ3NRL1ExSnd3RyIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJneWJlMTJAZ21hMGlsLmNvbSJ9LCJkZXZpY2UiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTYyODQxODY5MX0.QIyHjhnJ2mBJm1OOzVgnrRnOyzc9y1AfhLVMcxUgpyM
