
POST https://fresh-thinker-344120.df.r.appspot.com/api/user/registration
Content-Type: application/json

{   
    "username": "andress",
    "password": "1@Upper",
    "firstname": "juan",
    "lastname": "DelaCruz",
    "address": "juan@email.com",
    "contact": "+639777060593"

}

###
POST https://fresh-thinker-344120.df.r.appspot.com/api/user/login
Content-Type: application/json

{
  "username": "andress",
  "password": "1@Upper"
}

###
GET https://fresh-thinker-344120.df.r.appspot.com/api/user/information 
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMwYmM3YjUzZTNhZTAwMGFhNGY5MjMiLCJkZXZpY2UiOiJ2c2NvZGUtcmVzdGNsaWVudCIsInNob3AiOiI2MjMwYmM3YjUzZTNhZTAwMGFhNGY5MjQiLCJpYXQiOjE2NDczNjE2NDR9.IitXoQrTajyynFUjK4q7kwDPalTWwPBV12ZL10x0_gk"

###
PATCH http://localhost:8000/api/user/information 
Authorization: Bearerey eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJfaWQiOiI2MTEyMmYzMzg4ZTQ4ZDhkZjVlOWQ4OWEiLCJwYXNzd29yZCI6IiQyYSQxMCRidk5EUnBrNXlIeXh5bFZFS2I1V0RPcTI1dThOblV3ejVOajJOM2tSMk5CVVhKbnNRREw2ZSIsInNob3AiOiI2MTEyMmYzMzg4ZTQ4ZDhkZjVlOWQ4OWIifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg2MDM4NDl9.Ydfk450GWI4U_2oJ8MFCe4CAWiTvWqgJQp6bXCyFwsE
Content-Type: application/json

{    
    "firstname":"a"
}

###
GET http://localhost:8000/api/user/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJmb2xsb3dlZF9zaG9wcyI6W10sImluYm94IjpbXSwicHJvZmlsZUlNRyI6Imh0dHA6Ly9zbmFwLnNoby9zYW4uanBnIiwib3JkZXJzIjpbXSwiX2lkIjoiNjExMWMxOTcwYjllZDUxNWYzMjM0N2IxIiwidXNlcm5hbWUiOiJ1czJlcjAxMTIiLCJwYXNzd29yZCI6IiQyYSQxMCRSNjI4TU9DTFlydURoVGlGV2kzQ3p1WU1YODBIeW5TOTZtNFpTZ3FuSjhHU2w4dlI5UEdBaSIsImZpcnN0bmFtZSI6Imp1YW4iLCJsYXN0bmFtZSI6IkRlbGEgQ3J1eiIsImFkZHJlc3MiOiJqdWFuQGVtYWlsLmNvbSIsImNvbnRhY3QiOiIwOTk5MzMyMTQ1NiIsInNob3AiOiI2MTExYzE5NzBiOWVkNTE1ZjMyMzQ3YjIiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTEwVDAwOjAwOjIzLjY1OFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTEwVDAwOjAwOjIzLjY1OFoifSwiZGV2aWNlIjoidnNjb2RlLXJlc3RjbGllbnQiLCJpYXQiOjE2Mjg1NjUyNTB9.WDHP5zO0dkTHEAt2AupK03Lx6dqD4jx25AofUi9AXJ8
